services:
    rappi.cube_summation.input_as_string.adapter:
        class: RappiBundle\Processor\Adapter\CubeSummationProcessInputAsString

    rappi.cube_summation.handler:
        class: RappiBundle\Processor\CubeSummationProcessor
        arguments: ["@rappi.cube_summation.input_as_string.adapter"]
